name: Airtable Node.js

on:
  workflow_dispatch:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: echo $AIRTABLE_BASE_ID
      - run: npm ci
      - run: npm run start --if-present
      - run: npm test
