name: Airtable Node.js

on:
  workflow_dispatch:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: output envs
        run: echo $AIRTABLE_BASE_ID
      - name: add envs to .env
        run: | 
          touch .env
          echo AIRTABLE_KEY=${{ secrets.AIRTABLE_KEY }} >> .env
          echo AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }} >> .env
          cat .env
      - name: Install
        run: npm ci
      - name: Run Start
        run: npm run start --if-present
